<template>
  <div class="about" id="mountNode">
    <h1>This is an about page</h1>
  </div>
</template>
<script>
import G6 from "@antv/g6";
export default {
  data() {
    return {};
  },
  mounted() {
    this.$nextTick(() => {
      this.initG6();
    });
  },
  methods: {
    initG6() {
      let res = {
        code: 200,
        success: true,
        data: {
          linkList: [
            {
              sendTrafficMax: "507158",
              receiveTrafficMax: "57335852",
              leftIfIndex: "8",
              rightIfIndex: "29",
              adevId: -1,
              adevName: "2_PE.cncnet.net",
              adevIp: "192.168.0.2",
              zdevId: -1,
              zdevName: "3_P",
              zdevIp: "192.168.0.3",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/4",
              zdevPortIp: "10.2.3.2",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/0",
              adevPortIp: "10.2.3.1"
            },
            {
              sendTrafficMax: "77702",
              receiveTrafficMax: "75415",
              leftIfIndex: "9",
              rightIfIndex: "29",
              adevId: -1,
              adevName: "2_PE.cncnet.net",
              adevIp: "192.168.0.2",
              zdevId: -1,
              zdevName: "13_P",
              zdevIp: "192.168.0.13",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/4",
              zdevPortIp: "10.2.13.2",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/1",
              adevPortIp: "10.2.13.1"
            },
            {
              sendTrafficMax: "89118464",
              receiveTrafficMax: "27967706",
              leftIfIndex: "70",
              rightIfIndex: "30",
              adevId: -1,
              adevName: "12_PE.cncnet.net",
              adevIp: "192.168.0.12",
              zdevId: -1,
              zdevName: "3_P",
              zdevIp: "192.168.0.3",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/5",
              zdevPortIp: "10.3.12.1",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/0",
              adevPortIp: "10.3.12.2"
            },
            {
              sendTrafficMax: "34350",
              receiveTrafficMax: "20074",
              leftIfIndex: "71",
              rightIfIndex: "30",
              adevId: -1,
              adevName: "12_PE.cncnet.net",
              adevIp: "192.168.0.12",
              zdevId: -1,
              zdevName: "13_P",
              zdevIp: "192.168.0.13",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/5",
              zdevPortIp: "10.12.13.2",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/1",
              adevPortIp: "10.12.13.1"
            },
            {
              sendTrafficMax: "23245",
              receiveTrafficMax: "16599",
              leftIfIndex: "71",
              rightIfIndex: "52",
              adevId: -1,
              adevName: "7_PE.cuii.com",
              adevIp: "192.168.0.7",
              zdevId: -1,
              zdevName: "16_P",
              zdevIp: "192.168.0.16",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/1/4",
              zdevPortIp: "10.7.16.2",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/1",
              adevPortIp: "10.7.16.1"
            },
            {
              sendTrafficMax: "15723",
              receiveTrafficMax: "57324692",
              leftIfIndex: "70",
              rightIfIndex: "34",
              adevId: -1,
              adevName: "7_PE.cuii.com",
              adevIp: "192.168.0.7",
              zdevId: -1,
              zdevName: "6_P",
              zdevIp: "192.168.0.6",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/1/4",
              zdevPortIp: "10.6.7.1",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/0",
              adevPortIp: "10.6.7.2"
            },
            {
              sendTrafficMax: "41872",
              receiveTrafficMax: "23670",
              leftIfIndex: "11",
              rightIfIndex: "53",
              adevId: -1,
              adevName: "17_PE",
              adevIp: "192.168.0.17",
              zdevId: -1,
              zdevName: "16_P",
              zdevIp: "192.168.0.16",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/1/5",
              zdevPortIp: "10.16.17.1",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/1",
              adevPortIp: "10.16.17.2"
            },
            {
              sendTrafficMax: "88612864",
              receiveTrafficMax: "27825400",
              leftIfIndex: "10",
              rightIfIndex: "35",
              adevId: -1,
              adevName: "17_PE",
              adevIp: "192.168.0.17",
              zdevId: -1,
              zdevName: "6_P",
              zdevIp: "192.168.0.6",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/1/5",
              zdevPortIp: "10.6.17.1",
              adevPortId: -1,
              adevPortName: "TenGigE0/0/2/0",
              adevPortIp: "10.6.17.2"
            },
            {
              sendTrafficMax: "21417",
              receiveTrafficMax: "17282",
              leftIfIndex: "25",
              rightIfIndex: "25",
              adevId: -1,
              adevName: "3_P",
              adevIp: "192.168.0.3",
              zdevId: -1,
              zdevName: "13_P",
              zdevIp: "192.168.0.13",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/0",
              zdevPortIp: "10.3.13.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/0",
              adevPortIp: "10.3.13.1"
            },
            {
              sendTrafficMax: "60307040",
              receiveTrafficMax: "195115",
              leftIfIndex: "27",
              rightIfIndex: "27",
              adevId: -1,
              adevName: "3_P",
              adevIp: "192.168.0.3",
              zdevId: -1,
              zdevName: "10_PE",
              zdevIp: "192.168.0.10",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/2",
              zdevPortIp: "10.3.10.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/2",
              adevPortIp: "10.3.10.1"
            },
            {
              sendTrafficMax: "18467",
              receiveTrafficMax: "18470",
              leftIfIndex: "28",
              rightIfIndex: "28",
              adevId: -1,
              adevName: "3_P",
              adevIp: "192.168.0.3",
              zdevId: -1,
              zdevName: "20_PE",
              zdevIp: "192.168.0.20",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/3",
              zdevPortIp: "10.3.20.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/3",
              adevPortIp: "10.3.20.1"
            },
            {
              sendTrafficMax: "58863840",
              receiveTrafficMax: "58414024",
              leftIfIndex: "39",
              rightIfIndex: "8",
              adevId: -1,
              adevName: "3_P",
              adevIp: "192.168.0.3",
              zdevId: -1,
              zdevName: "5_P",
              zdevIp: "192.168.0.5",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/2",
              zdevPortIp: "10.3.5.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/1/1",
              adevPortIp: "10.3.5.1"
            },
            {
              sendTrafficMax: "23964",
              receiveTrafficMax: "46603",
              leftIfIndex: "43",
              rightIfIndex: "6",
              adevId: -1,
              adevName: "3_P",
              adevIp: "192.168.0.3",
              zdevId: -1,
              zdevName: "4_P",
              zdevIp: "192.168.0.4",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/1",
              zdevPortIp: "10.3.4.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/1/5",
              adevPortIp: "10.3.4.1"
            },
            {
              sendTrafficMax: "290657",
              receiveTrafficMax: "226220",
              leftIfIndex: "39",
              rightIfIndex: "8",
              adevId: -1,
              adevName: "13_P",
              adevIp: "192.168.0.13",
              zdevId: -1,
              zdevName: "15_P",
              zdevIp: "192.168.0.15",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/2",
              zdevPortIp: "10.13.15.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/1/1",
              adevPortIp: "10.13.15.1"
            },
            {
              sendTrafficMax: "183839",
              receiveTrafficMax: "224693",
              leftIfIndex: "28",
              rightIfIndex: "28",
              adevId: -1,
              adevName: "13_P",
              adevIp: "192.168.0.13",
              zdevId: -1,
              zdevName: "10_PE",
              zdevIp: "192.168.0.10",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/3",
              zdevPortIp: "10.10.13.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/3",
              adevPortIp: "10.10.13.2"
            },
            {
              sendTrafficMax: "33778",
              receiveTrafficMax: "38441",
              leftIfIndex: "27",
              rightIfIndex: "27",
              adevId: -1,
              adevName: "13_P",
              adevIp: "192.168.0.13",
              zdevId: -1,
              zdevName: "20_PE",
              zdevIp: "192.168.0.20",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/2",
              zdevPortIp: "10.13.20.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/2",
              adevPortIp: "10.13.20.1"
            },
            {
              sendTrafficMax: "24629",
              receiveTrafficMax: "41365",
              leftIfIndex: "43",
              rightIfIndex: "7",
              adevId: -1,
              adevName: "13_P",
              adevIp: "192.168.0.13",
              zdevId: -1,
              zdevName: "14_P",
              zdevIp: "192.168.0.14",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/1",
              zdevPortIp: "10.13.14.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/1/5",
              adevPortIp: "10.13.14.1"
            },
            {
              sendTrafficMax: "224724",
              receiveTrafficMax: "270876",
              leftIfIndex: "25",
              rightIfIndex: "7",
              adevId: -1,
              adevName: "16_P",
              adevIp: "192.168.0.16",
              zdevId: -1,
              zdevName: "15_P",
              zdevIp: "192.168.0.15",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/1",
              zdevPortIp: "10.15.16.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/1",
              adevPortIp: "10.15.16.2"
            },
            {
              sendTrafficMax: "26790",
              receiveTrafficMax: "30948",
              leftIfIndex: "50",
              rightIfIndex: "27",
              adevId: -1,
              adevName: "16_P",
              adevIp: "192.168.0.16",
              zdevId: -1,
              zdevName: "21_PE",
              zdevIp: "192.168.0.21",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/2",
              zdevPortIp: "10.16.21.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/1/2",
              adevPortIp: "10.16.21.1"
            },
            {
              sendTrafficMax: "194692",
              receiveTrafficMax: "218686",
              leftIfIndex: "51",
              rightIfIndex: "28",
              adevId: -1,
              adevName: "16_P",
              adevIp: "192.168.0.16",
              zdevId: -1,
              zdevName: "23_PE",
              zdevIp: "192.168.0.23",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/3",
              zdevPortIp: "10.16.23.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/1/3",
              adevPortIp: "10.16.23.1"
            },
            {
              sendTrafficMax: "21375",
              receiveTrafficMax: "17836",
              leftIfIndex: "49",
              rightIfIndex: "31",
              adevId: -1,
              adevName: "16_P",
              adevIp: "192.168.0.16",
              zdevId: -1,
              zdevName: "6_P",
              zdevIp: "192.168.0.6",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/1/1",
              zdevPortIp: "10.6.16.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/1/1",
              adevPortIp: "10.6.16.2"
            },
            {
              sendTrafficMax: "42989",
              receiveTrafficMax: "24710",
              leftIfIndex: "26",
              rightIfIndex: "8",
              adevId: -1,
              adevName: "16_P",
              adevIp: "192.168.0.16",
              zdevId: -1,
              zdevName: "14_P",
              zdevIp: "192.168.0.14",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/2",
              zdevPortIp: "10.14.16.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/2",
              adevPortIp: "10.14.16.2"
            },
            {
              sendTrafficMax: "78611",
              receiveTrafficMax: "21007",
              leftIfIndex: "9",
              rightIfIndex: "9",
              adevId: -1,
              adevName: "15_P",
              adevIp: "192.168.0.15",
              zdevId: -1,
              zdevName: "14_P",
              zdevIp: "192.168.0.14",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/3",
              zdevPortIp: "10.14.15.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/3",
              adevPortIp: "10.14.15.2"
            },
            {
              sendTrafficMax: "23456",
              receiveTrafficMax: "11429",
              leftIfIndex: "28",
              rightIfIndex: "33",
              adevId: -1,
              adevName: "21_PE",
              adevIp: "192.168.0.21",
              zdevId: -1,
              zdevName: "6_P",
              zdevIp: "192.168.0.6",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/1/3",
              zdevPortIp: "10.6.21.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/3",
              adevPortIp: "10.6.21.2"
            },
            {
              sendTrafficMax: "215200",
              receiveTrafficMax: "211370",
              leftIfIndex: "27",
              rightIfIndex: "32",
              adevId: -1,
              adevName: "23_PE",
              adevIp: "192.168.0.23",
              zdevId: -1,
              zdevName: "6_P",
              zdevIp: "192.168.0.6",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/1/2",
              zdevPortIp: "10.6.23.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/2",
              adevPortIp: "10.6.23.2"
            },
            {
              sendTrafficMax: "58893256",
              receiveTrafficMax: "58480532",
              leftIfIndex: "7",
              rightIfIndex: "25",
              adevId: -1,
              adevName: "5_P",
              adevIp: "192.168.0.5",
              zdevId: -1,
              zdevName: "6_P",
              zdevIp: "192.168.0.6",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/1",
              zdevPortIp: "10.5.6.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/1",
              adevPortIp: "10.5.6.1"
            },
            {
              sendTrafficMax: "16706",
              receiveTrafficMax: "16452",
              leftIfIndex: "9",
              rightIfIndex: "8",
              adevId: -1,
              adevName: "5_P",
              adevIp: "192.168.0.5",
              zdevId: -1,
              zdevName: "4_P",
              zdevIp: "192.168.0.4",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/3",
              zdevPortIp: "10.4.5.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/3",
              adevPortIp: "10.4.5.2"
            },
            {
              sendTrafficMax: "51325",
              receiveTrafficMax: "27753",
              leftIfIndex: "26",
              rightIfIndex: "7",
              adevId: -1,
              adevName: "6_P",
              adevIp: "192.168.0.6",
              zdevId: -1,
              zdevName: "4_P",
              zdevIp: "192.168.0.4",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/2",
              zdevPortIp: "10.4.6.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/2",
              adevPortIp: "10.4.6.2"
            },
            {
              sendTrafficMax: "17466",
              receiveTrafficMax: "17526",
              leftIfIndex: "5",
              rightIfIndex: "6",
              adevId: -1,
              adevName: "4_P",
              adevIp: "192.168.0.4",
              zdevId: -1,
              zdevName: "14_P",
              zdevIp: "192.168.0.14",
              zdevPortId: -1,
              zdevPortName: "GigabitEthernet1/0/0",
              zdevPortIp: "10.4.14.2",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/0",
              adevPortIp: "10.4.14.1"
            },
            {
              sendTrafficMax: "13093",
              receiveTrafficMax: "13403",
              leftIfIndex: "17",
              rightIfIndex: "217",
              adevId: -1,
              adevName: "4_P",
              adevIp: "192.168.0.4",
              zdevId: -1,
              zdevName: "H3C_CR16006-F",
              zdevIp: "192.168.0.33",
              zdevPortId: -1,
              zdevPortName: "Ten-GigabitEthernet2/2/1",
              zdevPortIp: "10.33.4.1",
              adevPortId: -1,
              adevPortName: "GigabitEthernet1/0/12",
              adevPortIp: "10.33.4.2"
            }
          ],
          deviceList: [
            {
              id: 1237,
              devName: "2_PE.cncnet.net",
              devIp: "192.168.0.2",
              devNet: "IP城域网",
              vendorName: "思科",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "9",
              y: "103",
              flag: ""
            },
            {
              id: 1238,
              devName: "12_PE.cncnet.net",
              devIp: "192.168.0.12",
              devNet: "IP城域网",
              vendorName: "思科",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "0",
              y: "196",
              flag: ""
            },
            {
              id: 1239,
              devName: "7_PE.cuii.com",
              devIp: "192.168.0.7",
              devNet: "IP城域网",
              vendorName: "思科",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "504",
              y: "68",
              flag: ""
            },
            {
              id: 1240,
              devName: "17_PE",
              devIp: "192.168.0.17",
              devNet: "IP城域网",
              vendorName: "思科",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "538",
              y: "162",
              flag: ""
            },
            {
              id: 1245,
              devName: "10_PE",
              devIp: "192.168.0.10",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "10",
              y: "304",
              flag: ""
            },
            {
              id: 1246,
              devName: "20_PE",
              devIp: "192.168.0.20",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "53",
              y: "371",
              flag: ""
            },
            {
              id: 1247,
              devName: "21_PE",
              devIp: "192.168.0.21",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "535",
              y: "283",
              flag: ""
            },
            {
              id: 1248,
              devName: "23_PE",
              devIp: "192.168.0.23",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "492",
              y: "359",
              flag: ""
            },
            {
              id: 1253,
              devName: "H3C_CR16006-F",
              devIp: "192.168.0.33",
              devNet: "IP城域网",
              vendorName: "华三",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "50",
              y: "28",
              flag: ""
            },
            {
              id: 1241,
              devName: "3_P",
              devIp: "192.168.0.3",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "221",
              y: "178",
              flag: ""
            },
            {
              id: 1242,
              devName: "13_P",
              devIp: "192.168.0.13",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "219",
              y: "262",
              flag: ""
            },
            {
              id: 1243,
              devName: "16_P",
              devIp: "192.168.0.16",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "352",
              y: "266",
              flag: ""
            },
            {
              id: 1244,
              devName: "15_P",
              devIp: "192.168.0.15",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "289",
              y: "346",
              flag: ""
            },
            {
              id: 1249,
              devName: "5_P",
              devIp: "192.168.0.5",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "289.4800240905188",
              y: "102.40260382629198",
              flag: ""
            },
            {
              id: 1250,
              devName: "6_P",
              devIp: "192.168.0.6",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "352",
              y: "178",
              flag: ""
            },
            {
              id: 1251,
              devName: "4_P",
              devIp: "192.168.0.4",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "290",
              y: "178",
              flag: ""
            },
            {
              id: 1252,
              devName: "14_P",
              devIp: "192.168.0.14",
              devNet: "IP城域网",
              vendorName: "华为",
              roomName: "",
              devRole: "核心路由器",
              devType: "CR",
              devIpMask: "",
              x: "289",
              y: "265",
              flag: ""
            }
          ],
          typeList: [{ dev_type: "CR" }]
        },
        msg: "操作成功"
      };
      res.data.deviceList.forEach(item => {
        item.label = item.devName;
        item.groupId = item.devType;
        console.log(item.label, item.groupId);
      });

      res.data.linkList.forEach(item => {
        item.source = item.adevName;
        item.target = item.zdevName;
        item.x = parseFloat(item.x);
        item.y = parseFloat(item.y);
        // console.log(item.label);
      });
      let data = {
        nodes: res.data.deviceList,
        edges: res.data.linkList,
        groups: [
          {
            id: "CR"
          }
        ]
      };
      //改造数据
      const graph = new G6.Graph({
        container: "mountNode",
        width: 1000,
        height: 800,
        pixelRatio: 2,
        modes: {
          default: [
            "drag-group",
            "collapse-expand-group"
            // "drag- node-with-group"
          ]
        },
        defaultNode: {
          shape: "circleNode"
        },
        defaultEdge: {
          color: "#bae7ff"
        }
      });
      graph.data(data);
      graph.render();
    }
  }
};
</script>
